services:
  - type: web
    name: sleepwise-backend
    env: python
    buildCommand: |
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5003
